<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Tucasana!</title>
</head>
<body>
<h1>Welcome to tucasana.com!</h1>
<p>This is a test page for our website, there will be more content added soon!</p>
<?php echo '<p>This line was generated by PHP code</p>'; ?> 
<form>
	<button formaction="login_page.php">Click here to go to the login page</button>
</form>
</body>
</html>